server:
  port: ${port:9091}

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/heima?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=true&useSSL=false
    username: root
    password: !Cm123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.itheima.user.pojo
  

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    instance:
      # 更倾向于使用ip地址，而不是host名
      prefer-ip-address: true
      # ip地址
      ip-address: 127.0.0.1
      # 续约间隔，默认30秒
      lease-renewal-interval-in-seconds: 5
      # 服务失效，默认90秒
      lease-expiration-duration-in-seconds: 5

test:
  name: heima
